### ISSUE TITLE
Suggestion: allow pinning uv version and cache it if given

### ISSUE THREAD

**Issue by ericbn** [hynek/setup-cached-uv#4]
Hi 👋 

This action could allow pinning the uv version, to avoid always getting the latest version with a potential breaking change. Something like:

```
    steps:
      - uses: hynek/setup-cached-uv@v1
        with:
          version: 0.1.31
```

Two side-effects of this feature to consider:
1. The installation process might need to download the binary directly or use `pip install` to allow installing a specific version.
2. The installed uv can be cached by using the uv version as part of the key, so next runs with the same uv version can take advantage of the cache instead of downloading/installing again.
