### ISSUE TITLE
Suggestion: if statement for caching 

### ISSUE THREAD

**Issue by henryiii** [hynek/setup-cached-uv#5]
Adding cached-uv sped up my pypy jobs (yay!), but slowed down all the other jobs, as it takes 2-10 seconds to restore the cache, and uv's just as fast without it if it doesn't have to build anything (so slower if you include the cache restore time, its almost always double the time). PyPy (and probably Python 3.13, forgot to check) need to build, so I'd like to have an `with: use-cache:` field that I could put a template into that would be true if I need the cache, and false if not (the cache is ~70MB per job, and I have a lot of jobs, so it would be nice to just do the important bits).

I can do this with something like this:

```yaml
    - name: Setup uv (uncached)
      uses: yezz123/setup-uv@v4
      if: "!startsWith(matrix.python-version, 'pypy')"

    - name: Setup uv (cached)
      uses: hynek/setup-cached-uv@v1
      if: "startsWith(matrix.python-version, 'pypy')"
      with:
        cache-suffix: -${{ matrix.python-version }}
```

but it's not as pretty to require two separate actions, IMO.

(FWIW, caching doesn't seem to be worth it for pixi or uv unless they have to build (which pixi never does...)
